[project]
name = "ds-container-workspace"
version = "0.1.1"
requires-python = ">=3.13"
license = { file = "LICENSE" }

dependencies = [
    "numpy==2.2.4",
    "pandas==2.2.3",
    "matplotlib==3.10.1",
    "seaborn==0.13.2",
    "ipykernel==6.29.5",
    "requests==2.32.3",
]

[tool.hatch.build.targets.wheel]
packages = ["tools"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
